#!/bin/bash

######################
# author: Sajad
# date: 26/04/25
#
# This script outputs the node health
#
######################

set -x 
# debug mode.

df -h 
# it shows available disk space.

free -g 
# memory space (RAM).

nproc 
# number of process utilized.

ps -ef | grep "amazon" 
# here '|' stands for pipe that connect first command to next command and grep to fetch only we are putting.
